package com.andromo.dev576782.app537736;

import com.actionbarsherlock.C0152R;

public final class hp {
    public static final int[] AdHubView;
    public static final int AdHubView_age = 3;
    public static final int AdHubView_gender = 2;
    public static final int AdHubView_interests = 4;
    public static final int AdHubView_inventoryId = 0;
    public static final int AdHubView_onlyXml = 1;
    public static final int[] AdsAttrs;
    public static final int AdsAttrs_adSize = 0;
    public static final int AdsAttrs_adSizes = 1;
    public static final int AdsAttrs_adUnitId = 2;
    public static final int[] AspectRatioImageView;
    public static final int AspectRatioImageView_fit = 0;
    public static final int AspectRatioImageView_maxHeightFactor = 3;
    public static final int AspectRatioImageView_maxSizeParent = 1;
    public static final int AspectRatioImageView_maxWidthFactor = 2;
    public static final int[] CustomWalletTheme;
    public static final int CustomWalletTheme_windowTransitionStyle = 0;
    public static final int[] DashboardSettings;
    public static final int DashboardSettings_button_grid_background = 32;
    public static final int DashboardSettings_button_grid_item_background = 33;
    public static final int DashboardSettings_button_grid_title_style = 34;
    public static final int DashboardSettings_custom_grid_background = 39;
    public static final int DashboardSettings_custom_item_background = 40;
    public static final int DashboardSettings_dashboard_background = 31;
    public static final int DashboardSettings_dashboard_list_item_style = 26;
    public static final int DashboardSettings_dashboard_list_title_style = 25;
    public static final int DashboardSettings_dashboard_logo_area_landscape_fit = 3;
    public static final int DashboardSettings_dashboard_logo_area_landscape_height = 21;
    public static final int DashboardSettings_dashboard_logo_area_landscape_maxHeightFactor = 9;
    public static final int DashboardSettings_dashboard_logo_area_landscape_maxSizeParent = 5;
    public static final int DashboardSettings_dashboard_logo_area_landscape_maxWidthFactor = 7;
    public static final int DashboardSettings_dashboard_logo_area_landscape_weight = 22;
    public static final int DashboardSettings_dashboard_logo_area_landscape_width = 20;
    public static final int DashboardSettings_dashboard_logo_area_portrait_fit = 2;
    public static final int DashboardSettings_dashboard_logo_area_portrait_height = 16;
    public static final int DashboardSettings_dashboard_logo_area_portrait_maxHeightFactor = 8;
    public static final int DashboardSettings_dashboard_logo_area_portrait_maxSizeParent = 4;
    public static final int DashboardSettings_dashboard_logo_area_portrait_maxWidthFactor = 6;
    public static final int DashboardSettings_dashboard_logo_area_portrait_weight = 17;
    public static final int DashboardSettings_dashboard_logo_area_portrait_width = 15;
    public static final int DashboardSettings_dashboard_logo_landscape_image_alignment = 13;
    public static final int DashboardSettings_dashboard_logo_landscape_image_drawable = 11;
    public static final int DashboardSettings_dashboard_logo_portrait_image_alignment = 12;
    public static final int DashboardSettings_dashboard_logo_portrait_image_drawable = 10;
    public static final int DashboardSettings_dashboard_panel_item_subtitle_color = 1;
    public static final int DashboardSettings_dashboard_panel_item_title_color = 0;
    public static final int DashboardSettings_gallery_grid_background = 35;
    public static final int DashboardSettings_gallery_image_background = 36;
    public static final int DashboardSettings_gallery_text_only_background = 37;
    public static final int DashboardSettings_list_footer_enabled = 28;
    public static final int DashboardSettings_list_panel_background = 27;
    public static final int DashboardSettings_logo_area_landscape_visibility = 23;
    public static final int DashboardSettings_logo_area_portrait_visibility = 18;
    public static final int DashboardSettings_logo_background_color = 14;
    public static final int DashboardSettings_logo_landscape_image_visibility = 24;
    public static final int DashboardSettings_logo_portrait_image_visibility = 19;
    public static final int DashboardSettings_panel_background_color = 38;
    public static final int DashboardSettings_panel_border_color = 30;
    public static final int DashboardSettings_panel_style_list_paddingTopBottom = 29;
    public static final int[] GridLayout;
    public static final int[] GridLayout_Layout;
    public static final int GridLayout_Layout_android_layout_height = 1;
    public static final int GridLayout_Layout_android_layout_margin = 2;
    public static final int GridLayout_Layout_android_layout_marginBottom = 6;
    public static final int GridLayout_Layout_android_layout_marginLeft = 3;
    public static final int GridLayout_Layout_android_layout_marginRight = 5;
    public static final int GridLayout_Layout_android_layout_marginTop = 4;
    public static final int GridLayout_Layout_android_layout_width = 0;
    public static final int GridLayout_Layout_layout_column = 9;
    public static final int GridLayout_Layout_layout_columnSpan = 10;
    public static final int GridLayout_Layout_layout_gravity = 11;
    public static final int GridLayout_Layout_layout_row = 7;
    public static final int GridLayout_Layout_layout_rowSpan = 8;
    public static final int GridLayout_alignmentMode = 4;
    public static final int GridLayout_columnCount = 2;
    public static final int GridLayout_columnOrderPreserved = 6;
    public static final int GridLayout_orientation = 0;
    public static final int GridLayout_rowCount = 1;
    public static final int GridLayout_rowOrderPreserved = 5;
    public static final int GridLayout_useDefaultMargins = 3;
    public static final int[] LoadingImageView;
    public static final int LoadingImageView_circleCrop = 2;
    public static final int LoadingImageView_imageAspectRatio = 1;
    public static final int LoadingImageView_imageAspectRatioAdjust = 0;
    public static final int[] MapAttrs;
    public static final int MapAttrs_ambientEnabled = 16;
    public static final int MapAttrs_cameraBearing = 1;
    public static final int MapAttrs_cameraTargetLat = 2;
    public static final int MapAttrs_cameraTargetLng = 3;
    public static final int MapAttrs_cameraTilt = 4;
    public static final int MapAttrs_cameraZoom = 5;
    public static final int MapAttrs_liteMode = 6;
    public static final int MapAttrs_mapType = 0;
    public static final int MapAttrs_uiCompass = 7;
    public static final int MapAttrs_uiMapToolbar = 15;
    public static final int MapAttrs_uiRotateGestures = 8;
    public static final int MapAttrs_uiScrollGestures = 9;
    public static final int MapAttrs_uiTiltGestures = 10;
    public static final int MapAttrs_uiZoomControls = 11;
    public static final int MapAttrs_uiZoomGestures = 12;
    public static final int MapAttrs_useViewLifecycle = 13;
    public static final int MapAttrs_zOrderOnTop = 14;
    public static final int[] ScrollableDashboardLayout;
    public static final int ScrollableDashboardLayout_allowSingleColumnUpTo = 2;
    public static final int ScrollableDashboardLayout_centerLastRow = 10;
    public static final int ScrollableDashboardLayout_margin_bottom = 6;
    public static final int ScrollableDashboardLayout_margin_left = 3;
    public static final int ScrollableDashboardLayout_margin_right = 5;
    public static final int ScrollableDashboardLayout_margin_top = 4;
    public static final int ScrollableDashboardLayout_maxColumnWidth = 7;
    public static final int ScrollableDashboardLayout_maxColumns = 1;
    public static final int ScrollableDashboardLayout_minColumns = 0;
    public static final int ScrollableDashboardLayout_minHorizontalGap = 8;
    public static final int ScrollableDashboardLayout_minVerticalGap = 9;
    public static final int ScrollableDashboardLayout_preferFullerLastRows = 11;
    public static final int ScrollableDashboardLayout_unevenGridPenalty = 12;
    public static final int[] SherlockActionBar;
    public static final int SherlockActionBar_background = 2;
    public static final int SherlockActionBar_backgroundSplit = 3;
    public static final int SherlockActionBar_backgroundStacked = 12;
    public static final int SherlockActionBar_customNavigationLayout = 13;
    public static final int SherlockActionBar_displayOptions = 7;
    public static final int SherlockActionBar_divider = 5;
    public static final int SherlockActionBar_height = 4;
    public static final int SherlockActionBar_homeLayout = 14;
    public static final int SherlockActionBar_icon = 10;
    public static final int SherlockActionBar_indeterminateProgressStyle = 16;
    public static final int SherlockActionBar_itemPadding = 18;
    public static final int SherlockActionBar_logo = 11;
    public static final int SherlockActionBar_navigationMode = 6;
    public static final int SherlockActionBar_progressBarPadding = 17;
    public static final int SherlockActionBar_progressBarStyle = 15;
    public static final int SherlockActionBar_subtitle = 9;
    public static final int SherlockActionBar_subtitleTextStyle = 1;
    public static final int SherlockActionBar_title = 8;
    public static final int SherlockActionBar_titleTextStyle = 0;
    public static final int[] SherlockActionMenuItemView;
    public static final int SherlockActionMenuItemView_android_minWidth = 0;
    public static final int[] SherlockActionMode;
    public static final int SherlockActionMode_background = 2;
    public static final int SherlockActionMode_backgroundSplit = 3;
    public static final int SherlockActionMode_height = 4;
    public static final int SherlockActionMode_subtitleTextStyle = 1;
    public static final int SherlockActionMode_titleTextStyle = 0;
    public static final int[] SherlockActivityChooserView;
    public static final int SherlockActivityChooserView_android_background = 0;
    public static final int SherlockActivityChooserView_expandActivityOverflowButtonDrawable = 2;
    public static final int SherlockActivityChooserView_initialActivityCount = 1;
    public static final int[] SherlockMenuGroup;
    public static final int SherlockMenuGroup_android_checkableBehavior = 5;
    public static final int SherlockMenuGroup_android_enabled = 0;
    public static final int SherlockMenuGroup_android_id = 1;
    public static final int SherlockMenuGroup_android_menuCategory = 3;
    public static final int SherlockMenuGroup_android_orderInCategory = 4;
    public static final int SherlockMenuGroup_android_visible = 2;
    public static final int[] SherlockMenuItem;
    public static final int SherlockMenuItem_android_actionLayout = 14;
    public static final int SherlockMenuItem_android_actionProviderClass = 16;
    public static final int SherlockMenuItem_android_actionViewClass = 15;
    public static final int SherlockMenuItem_android_alphabeticShortcut = 9;
    public static final int SherlockMenuItem_android_checkable = 11;
    public static final int SherlockMenuItem_android_checked = 3;
    public static final int SherlockMenuItem_android_enabled = 1;
    public static final int SherlockMenuItem_android_icon = 0;
    public static final int SherlockMenuItem_android_id = 2;
    public static final int SherlockMenuItem_android_menuCategory = 5;
    public static final int SherlockMenuItem_android_numericShortcut = 10;
    public static final int SherlockMenuItem_android_onClick = 12;
    public static final int SherlockMenuItem_android_orderInCategory = 6;
    public static final int SherlockMenuItem_android_showAsAction = 13;
    public static final int SherlockMenuItem_android_title = 7;
    public static final int SherlockMenuItem_android_titleCondensed = 8;
    public static final int SherlockMenuItem_android_visible = 4;
    public static final int[] SherlockMenuView;
    public static final int SherlockMenuView_headerBackground = 3;
    public static final int SherlockMenuView_horizontalDivider = 1;
    public static final int SherlockMenuView_itemBackground = 4;
    public static final int SherlockMenuView_itemIconDisabledAlpha = 6;
    public static final int SherlockMenuView_itemTextAppearance = 0;
    public static final int SherlockMenuView_preserveIconSpacing = 7;
    public static final int SherlockMenuView_verticalDivider = 2;
    public static final int SherlockMenuView_windowAnimationStyle = 5;
    public static final int[] SherlockSearchView;
    public static final int SherlockSearchView_android_imeOptions = 2;
    public static final int SherlockSearchView_android_inputType = 1;
    public static final int SherlockSearchView_android_maxWidth = 0;
    public static final int SherlockSearchView_iconifiedByDefault = 3;
    public static final int SherlockSearchView_queryHint = 4;
    public static final int[] SherlockSpinner;
    public static final int SherlockSpinner_android_dropDownHorizontalOffset = 5;
    public static final int SherlockSpinner_android_dropDownSelector = 1;
    public static final int SherlockSpinner_android_dropDownVerticalOffset = 6;
    public static final int SherlockSpinner_android_dropDownWidth = 4;
    public static final int SherlockSpinner_android_gravity = 0;
    public static final int SherlockSpinner_android_popupBackground = 2;
    public static final int SherlockSpinner_android_popupPromptView = 7;
    public static final int SherlockSpinner_android_prompt = 3;
    public static final int[] SherlockTheme;
    public static final int SherlockTheme_actionBarDivider = 9;
    public static final int SherlockTheme_actionBarItemBackground = 10;
    public static final int SherlockTheme_actionBarSize = 8;
    public static final int SherlockTheme_actionBarSplitStyle = 6;
    public static final int SherlockTheme_actionBarStyle = 5;
    public static final int SherlockTheme_actionBarTabBarStyle = 2;
    public static final int SherlockTheme_actionBarTabStyle = 1;
    public static final int SherlockTheme_actionBarTabTextStyle = 3;
    public static final int SherlockTheme_actionBarWidgetTheme = 7;
    public static final int SherlockTheme_actionButtonStyle = 53;
    public static final int SherlockTheme_actionDropDownStyle = 52;
    public static final int SherlockTheme_actionMenuTextAppearance = 11;
    public static final int SherlockTheme_actionMenuTextColor = 12;
    public static final int SherlockTheme_actionModeBackground = 15;
    public static final int SherlockTheme_actionModeCloseButtonStyle = 14;
    public static final int SherlockTheme_actionModeCloseDrawable = 17;
    public static final int SherlockTheme_actionModePopupWindowStyle = 19;
    public static final int SherlockTheme_actionModeShareDrawable = 18;
    public static final int SherlockTheme_actionModeSplitBackground = 16;
    public static final int SherlockTheme_actionModeStyle = 13;
    public static final int SherlockTheme_actionOverflowButtonStyle = 4;
    public static final int SherlockTheme_actionSpinnerItemStyle = 58;
    public static final int SherlockTheme_activatedBackgroundIndicator = 66;
    public static final int SherlockTheme_activityChooserViewStyle = 65;
    public static final int SherlockTheme_android_windowIsFloating = 0;
    public static final int SherlockTheme_buttonStyleSmall = 20;
    public static final int SherlockTheme_dividerVertical = 51;
    public static final int SherlockTheme_dropDownListViewStyle = 55;
    public static final int SherlockTheme_dropdownListPreferredItemHeight = 57;
    public static final int SherlockTheme_homeAsUpIndicator = 54;
    public static final int SherlockTheme_listPopupWindowStyle = 64;
    public static final int SherlockTheme_listPreferredItemHeightSmall = 45;
    public static final int SherlockTheme_listPreferredItemPaddingLeft = 46;
    public static final int SherlockTheme_listPreferredItemPaddingRight = 47;
    public static final int SherlockTheme_popupMenuStyle = 56;
    public static final int SherlockTheme_searchAutoCompleteTextView = 31;
    public static final int SherlockTheme_searchDropdownBackground = 32;
    public static final int SherlockTheme_searchResultListItemHeight = 42;
    public static final int SherlockTheme_searchViewCloseIcon = 33;
    public static final int SherlockTheme_searchViewEditQuery = 37;
    public static final int SherlockTheme_searchViewEditQueryBackground = 38;
    public static final int SherlockTheme_searchViewGoIcon = 34;
    public static final int SherlockTheme_searchViewSearchIcon = 35;
    public static final int SherlockTheme_searchViewTextField = 39;
    public static final int SherlockTheme_searchViewTextFieldRight = 40;
    public static final int SherlockTheme_searchViewVoiceIcon = 36;
    public static final int SherlockTheme_selectableItemBackground = 21;
    public static final int SherlockTheme_spinnerDropDownItemStyle = 30;
    public static final int SherlockTheme_spinnerItemStyle = 29;
    public static final int SherlockTheme_textAppearanceLargePopupMenu = 23;
    public static final int SherlockTheme_textAppearanceListItemSmall = 48;
    public static final int SherlockTheme_textAppearanceSearchResultSubtitle = 44;
    public static final int SherlockTheme_textAppearanceSearchResultTitle = 43;
    public static final int SherlockTheme_textAppearanceSmall = 25;
    public static final int SherlockTheme_textAppearanceSmallPopupMenu = 24;
    public static final int SherlockTheme_textColorPrimary = 26;
    public static final int SherlockTheme_textColorPrimaryDisableOnly = 27;
    public static final int SherlockTheme_textColorPrimaryInverse = 28;
    public static final int SherlockTheme_textColorSearchUrl = 41;
    public static final int SherlockTheme_windowActionBar = 60;
    public static final int SherlockTheme_windowActionBarOverlay = 61;
    public static final int SherlockTheme_windowActionModeOverlay = 62;
    public static final int SherlockTheme_windowContentOverlay = 22;
    public static final int SherlockTheme_windowMinWidthMajor = 49;
    public static final int SherlockTheme_windowMinWidthMinor = 50;
    public static final int SherlockTheme_windowNoTitle = 59;
    public static final int SherlockTheme_windowSplitActionBar = 63;
    public static final int[] SherlockView;
    public static final int SherlockView_android_focusable = 0;
    public static final int[] SignInButton;
    public static final int SignInButton_buttonSize = 0;
    public static final int SignInButton_colorScheme = 1;
    public static final int SignInButton_scopeUris = 2;
    public static final int[] SlidingPanel;
    public static final int SlidingPanel_speed = 0;
    public static final int SlidingPanel_targetHeight = 1;
    public static final int[] Theme_Andromo;
    public static final int Theme_Andromo_ic_andromo_menu_save = 0;
    public static final int[] WalletFragmentOptions;
    public static final int WalletFragmentOptions_appTheme = 0;
    public static final int WalletFragmentOptions_environment = 1;
    public static final int WalletFragmentOptions_fragmentMode = 3;
    public static final int WalletFragmentOptions_fragmentStyle = 2;
    public static final int[] WalletFragmentStyle;
    public static final int WalletFragmentStyle_buyButtonAppearance = 3;
    public static final int WalletFragmentStyle_buyButtonHeight = 0;
    public static final int WalletFragmentStyle_buyButtonText = 2;
    public static final int WalletFragmentStyle_buyButtonWidth = 1;
    public static final int WalletFragmentStyle_maskedWalletDetailsBackground = 6;
    public static final int WalletFragmentStyle_maskedWalletDetailsButtonBackground = 8;
    public static final int WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance = 7;
    public static final int WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance = 5;
    public static final int WalletFragmentStyle_maskedWalletDetailsLogoImageType = 10;
    public static final int WalletFragmentStyle_maskedWalletDetailsLogoTextColor = 9;
    public static final int WalletFragmentStyle_maskedWalletDetailsTextAppearance = 4;

    static {
        AdHubView = new int[]{2130772178, 2130772179, 2130772180, 2130772181, 2130772182};
        AdsAttrs = new int[]{2130771968, 2130771969, 2130771970};
        AspectRatioImageView = new int[]{2130772132, 2130772133, 2130772134, 2130772135};
        int[] iArr = new int[WalletFragmentStyle_buyButtonWidth];
        iArr[WalletFragmentStyle_buyButtonHeight] = 2130772009;
        CustomWalletTheme = iArr;
        DashboardSettings = new int[]{2130772136, 2130772137, 2130772138, 2130772139, 2130772140, 2130772141, 2130772142, 2130772143, 2130772144, 2130772145, 2130772146, 2130772147, 2130772148, 2130772149, 2130772150, 2130772151, 2130772152, 2130772153, 2130772154, 2130772155, 2130772156, 2130772157, 2130772158, 2130772159, 2130772160, 2130772161, 2130772162, 2130772163, 2130772164, 2130772165, 2130772166, 2130772167, 2130772168, 2130772169, 2130772170, 2130772171, 2130772172, 2130772173, 2130772174, 2130772175, 2130772176};
        GridLayout = new int[]{2130772010, 2130772011, 2130772012, 2130772013, 2130772014, 2130772015, 2130772016};
        GridLayout_Layout = new int[]{16842996, 16842997, 16842998, 16842999, 16843000, 16843001, 16843002, 2130772017, 2130772018, 2130772019, 2130772020, 2130772021};
        LoadingImageView = new int[]{2130771974, 2130771975, 2130771976};
        MapAttrs = new int[]{2130771977, 2130771978, 2130771979, 2130771980, 2130771981, 2130771982, 2130771983, 2130771984, 2130771985, 2130771986, 2130771987, 2130771988, 2130771989, 2130771990, 2130771991, 2130771992, 2130771993};
        ScrollableDashboardLayout = new int[]{2130772022, 2130772023, 2130772024, 2130772025, 2130772026, 2130772027, 2130772028, 2130772029, 2130772030, 2130772031, 2130772032, 2130772033, 2130772034};
        SherlockActionBar = new int[]{C0152R.attr.titleTextStyle, C0152R.attr.subtitleTextStyle, C0152R.attr.background, C0152R.attr.backgroundSplit, C0152R.attr.height, C0152R.attr.divider, C0152R.attr.navigationMode, C0152R.attr.displayOptions, C0152R.attr.title, C0152R.attr.subtitle, C0152R.attr.icon, C0152R.attr.logo, C0152R.attr.backgroundStacked, C0152R.attr.customNavigationLayout, C0152R.attr.homeLayout, C0152R.attr.progressBarStyle, C0152R.attr.indeterminateProgressStyle, C0152R.attr.progressBarPadding, C0152R.attr.itemPadding};
        iArr = new int[WalletFragmentStyle_buyButtonWidth];
        iArr[WalletFragmentStyle_buyButtonHeight] = 16843071;
        SherlockActionMenuItemView = iArr;
        SherlockActionMode = new int[]{C0152R.attr.titleTextStyle, C0152R.attr.subtitleTextStyle, C0152R.attr.background, C0152R.attr.backgroundSplit, C0152R.attr.height};
        SherlockActivityChooserView = new int[]{16842964, C0152R.attr.initialActivityCount, C0152R.attr.expandActivityOverflowButtonDrawable};
        SherlockMenuGroup = new int[]{16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
        SherlockMenuItem = new int[]{16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, 16843481, 16843515, 16843516, 16843657};
        SherlockMenuView = new int[]{C0152R.attr.itemTextAppearance, C0152R.attr.horizontalDivider, C0152R.attr.verticalDivider, C0152R.attr.headerBackground, C0152R.attr.itemBackground, C0152R.attr.windowAnimationStyle, C0152R.attr.itemIconDisabledAlpha, C0152R.attr.preserveIconSpacing};
        SherlockSearchView = new int[]{16843039, 16843296, 16843364, C0152R.attr.iconifiedByDefault, C0152R.attr.queryHint};
        SherlockSpinner = new int[]{16842927, 16843125, 16843126, 16843131, 16843362, 16843436, 16843437, 18219089};
        SherlockTheme = new int[]{16842839, C0152R.attr.actionBarTabStyle, C0152R.attr.actionBarTabBarStyle, C0152R.attr.actionBarTabTextStyle, C0152R.attr.actionOverflowButtonStyle, C0152R.attr.actionBarStyle, C0152R.attr.actionBarSplitStyle, C0152R.attr.actionBarWidgetTheme, C0152R.attr.actionBarSize, C0152R.attr.actionBarDivider, C0152R.attr.actionBarItemBackground, C0152R.attr.actionMenuTextAppearance, C0152R.attr.actionMenuTextColor, C0152R.attr.actionModeStyle, C0152R.attr.actionModeCloseButtonStyle, C0152R.attr.actionModeBackground, C0152R.attr.actionModeSplitBackground, C0152R.attr.actionModeCloseDrawable, C0152R.attr.actionModeShareDrawable, C0152R.attr.actionModePopupWindowStyle, C0152R.attr.buttonStyleSmall, C0152R.attr.selectableItemBackground, C0152R.attr.windowContentOverlay, C0152R.attr.textAppearanceLargePopupMenu, C0152R.attr.textAppearanceSmallPopupMenu, C0152R.attr.textAppearanceSmall, C0152R.attr.textColorPrimary, C0152R.attr.textColorPrimaryDisableOnly, C0152R.attr.textColorPrimaryInverse, C0152R.attr.spinnerItemStyle, C0152R.attr.spinnerDropDownItemStyle, C0152R.attr.searchAutoCompleteTextView, C0152R.attr.searchDropdownBackground, C0152R.attr.searchViewCloseIcon, C0152R.attr.searchViewGoIcon, C0152R.attr.searchViewSearchIcon, C0152R.attr.searchViewVoiceIcon, C0152R.attr.searchViewEditQuery, C0152R.attr.searchViewEditQueryBackground, C0152R.attr.searchViewTextField, C0152R.attr.searchViewTextFieldRight, C0152R.attr.textColorSearchUrl, C0152R.attr.searchResultListItemHeight, C0152R.attr.textAppearanceSearchResultTitle, C0152R.attr.textAppearanceSearchResultSubtitle, C0152R.attr.listPreferredItemHeightSmall, C0152R.attr.listPreferredItemPaddingLeft, C0152R.attr.listPreferredItemPaddingRight, C0152R.attr.textAppearanceListItemSmall, C0152R.attr.windowMinWidthMajor, C0152R.attr.windowMinWidthMinor, C0152R.attr.dividerVertical, C0152R.attr.actionDropDownStyle, C0152R.attr.actionButtonStyle, C0152R.attr.homeAsUpIndicator, C0152R.attr.dropDownListViewStyle, C0152R.attr.popupMenuStyle, C0152R.attr.dropdownListPreferredItemHeight, C0152R.attr.actionSpinnerItemStyle, C0152R.attr.windowNoTitle, C0152R.attr.windowActionBar, C0152R.attr.windowActionBarOverlay, C0152R.attr.windowActionModeOverlay, C0152R.attr.windowSplitActionBar, C0152R.attr.listPopupWindowStyle, C0152R.attr.activityChooserViewStyle, C0152R.attr.activatedBackgroundIndicator};
        iArr = new int[WalletFragmentStyle_buyButtonWidth];
        iArr[WalletFragmentStyle_buyButtonHeight] = 16842970;
        SherlockView = iArr;
        SignInButton = new int[]{2130771971, 2130771972, 2130771973};
        SlidingPanel = new int[]{2130772183, 2130772184};
        iArr = new int[WalletFragmentStyle_buyButtonWidth];
        iArr[WalletFragmentStyle_buyButtonHeight] = 2130772177;
        Theme_Andromo = iArr;
        WalletFragmentOptions = new int[]{2130771994, 2130771995, 2130771996, 2130771997};
        WalletFragmentStyle = new int[]{2130771998, 2130771999, 2130772000, 2130772001, 2130772002, 2130772003, 2130772004, 2130772005, 2130772006, 2130772007, 2130772008};
    }
}
