package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.C0583o;
import com.google.android.gms.common.api.C0638p;
import com.google.android.gms.common.api.C0662r;
import com.google.android.gms.common.api.Status;

public final class au extends C0583o {
    final Status f4575a;

    public final Integer m5173a() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final void m5174a(C0638p c0638p) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final void m5175a(C0662r c0662r) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }
}
